version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:
      - ./data_influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana/:/var/lib/grafana

  server_http:
    build: ./server_http/
    env_file:
      - .env
    ports:
      - "$HTTP_IP:$HTTP_PORT:80" #localip:localport:containerport
    links:
      - influxdb
    volumes:
      - "./server_http/src/:/server_http/src"
  # server_mqtt:
  #   build: ./server_mqtt/
  #   env_file:
  #     - .env
  #   ports:
  #     - "$MQTT_IP:$MQTT_PORT:80"
  #   links:
  #     - influxdb
  #   volumes:
  #     - "./server_mqtt/src/:/server_mqtt/src"
  # server_udp:
  #   build: ./server_udp/
  #   env_file:
  #     - .env
  #   ports:
  #     - "$UDP_IP:$UDP_PORT:80"
  #   links:
  #     - influxdb
  #   volumes:
  #     - "./server_udp/src/:/server_udp/src"
