version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:
      - ./data_influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana/:/var/lib/grafana
  server:
    build: ./server/
    ports:
      - "5000:5000"
    links:
      - influxdb
    volumes:
      - "./server/src/:/server/src"
