version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:
      - ./data_influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana/:/var/lib/grafana

  server_http:
    build: ./server_http/
    env_file:
      - .env
    ports:
      - "$HTTP_IP:$HTTP_PORT:80" #localip:localport:containerport
    links:
      - influxdb
    volumes:
      - "./server_http/src/:/server_http/src"
